---
project_name: aqua-proxy
archives:
- name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
builds:
- binary: aqua-proxy
  main: cmd/aqua-proxy/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
release:
  prerelease: true
