---
project_name: clivm-proxy
archives:
- name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
builds:
- binary: clivm-proxy
  main: cmd/clivm-proxy/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
release:
  prerelease: true
  header: |
    [Pull Requests](https://github.com/clivm/clivm-proxy/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/clivm/clivm-proxy/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/clivm/clivm-proxy/compare/{{.PreviousTag}}...{{.Tag}}
